Update reusable-build-and-publish.yml
cleanup steps added

diff --git a/.github/workflows/reusable-build-and-publish.yml b/.github/workflows/reusable-build-and-publish.yml
--- a/.github/workflows/reusable-build-and-publish.yml
+++ b/.github/workflows/reusable-build-and-publish.yml
@@ -80,6 +80,19 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      # Step to free up disk space
+      - name: Free disk space
+        run: |
+          sudo swapoff -a
+          sudo rm -f /swapfile
+          sudo apt clean
+          docker rmi $(docker image ls -aq) || true
+          df -h
+            
+      # Step to monitor disk space before build
+      - name: Check disk space before build
+        run: df -h
+
       # Step to build and push the Docker image
       - name: Build and push Docker image
         continue-on-error: true
@@ -91,6 +104,15 @@ jobs:
           docker push ghcr.io/${OWNER_LC}/container-images/${IMAGE_NAME}:${{ env.VERSION }}
           docker push ghcr.io/${OWNER_LC}/container-images/${IMAGE_NAME}:${{ github.sha }}
         # This builds the Docker image and tags it with the latest version, current version, and commit SHA
+      
+        # Step to clean up Docker images
+      - name: Clean up Docker images
+        run: |
+          docker rmi $(docker images -q) || true
+
+      # Step to monitor disk space after build
+      - name: Check disk space after build
+        run: df -h
 
       # Step to install bumpversion
       - name: Install bumpversion
