test

diff --git a/.github/workflows/reusable-build-and-publishv2.yml b/.github/workflows/reusable-build-and-publishv2.yml
--- a/.github/workflows/reusable-build-and-publishv2.yml
+++ b/.github/workflows/reusable-build-and-publishv2.yml
@@ -93,19 +93,19 @@ jobs:
       #- name: Debug - List directory contents
       #  run: ls -R
 
-      - name: Debug - List files under matrix folder
-        run: ls -R ${{ matrix.folder }}
+      # - name: Debug - List files under matrix folder
+      #   run: ls -R ${{ matrix.folder }}
 
-      - name: Debug - Show VERSION file content before bumpversion
-        run: cat ${{ matrix.folder }}/VERSION
+      # - name: Debug - Show VERSION file content before bumpversion
+      #   run: cat ${{ matrix.folder }}/VERSION
 
-      - name: Verify VERSION file exists
-        run: |
-          if [ ! -f "${{ matrix.folder }}/VERSION" ]; then
-            echo "VERSION file not found"
-            exit 1
-          fi
-          echo "VERSION file exists"
+      # - name: Verify VERSION file exists
+      #   run: |
+      #     if [ ! -f "${{ matrix.folder }}/VERSION" ]; then
+      #       echo "VERSION file not found"
+      #       exit 1
+      #     fi
+      #     echo "VERSION file exists"
 
       - name: Bump version
         run: |
@@ -118,7 +118,7 @@ jobs:
       - name: Sanitize tag name
         id: sanitize_tag_name
         run: |
-          SANITIZED_TAG=$(echo "${{ matrix.folder }}-v${{ env.NEW_VERSION }}" | sed 's/[\/.]/-/g')
+          SANITIZED_TAG=$(echo "${{ matrix.folder }}-v${{ env.NEW_VERSION }}" | sed 's/[^a-zA-Z0-9_-]/-/g')
           echo "SANITIZED_TAG=$SANITIZED_TAG" >> $GITHUB_ENV
 
       - name: Commit and push changes
@@ -132,5 +132,5 @@ jobs:
           NEW_VERSION: ${{ env.NEW_VERSION }}
           SANITIZED_TAG: ${{ env.SANITIZED_TAG }}
 
-      - name: Debug - Show VERSION file content after bumpversion
-        run: cat ${{ matrix.folder }}/VERSION
+      #- name: Debug - Show VERSION file content after bumpversion
+      #  run: cat ${{ matrix.folder }}/VERSION
