Update reusable-build-and-publish.yml

diff --git a/.github/workflows/reusable-build-and-publish.yml b/.github/workflows/reusable-build-and-publish.yml
--- a/.github/workflows/reusable-build-and-publish.yml
+++ b/.github/workflows/reusable-build-and-publish.yml
@@ -1,4 +1,5 @@
 name: ♻️ Reusable - 🚀 Build/Publish/Tag/Version Docker Images
+# 14GB of free space for both private & public repos github runners
 on:
   workflow_call:
     inputs:
@@ -46,6 +47,42 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         # Step to checkout the repository
+  
+      # debug: Step to monitor disk space before cleanup
+      - name: Check disk space before build
+        run: df -h
+
+      # Step to free up disk space manually
+      #- name: Free disk space
+      #  run: |
+      #    sudo swapoff -a
+      #    sudo rm -f /swapfile
+      #    sudo apt clean
+      #    docker rmi $(docker image ls -aq) || true
+      #    df -h
+
+      # https://github.com/jlumbroso/free-disk-space
+      - name: Free disk space
+        uses: jlumbroso/free-disk-space@main
+        with:
+          # this might remove tools that are actually needed,
+          # if set to "true" but frees about 6 GB
+          tool-cache: false
+          # all of these default to true, but feel free to set to
+          # "false" if necessary for workflow
+          android: true
+          dotnet: true
+          haskell: true
+          large-packages: true
+          docker-images: false
+          swap-storage: true      
+
+      # debug: Step to monitor disk space before build after cleanup
+      - name: Check disk space before build
+        run: df -h
+
+
+
 
       # Step to set the repository owner name in lowercase 
       # notes: 
@@ -79,39 +116,6 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-    
-      # debug: Step to monitor disk space before cleanup
-      - name: Check disk space before build
-        run: df -h
-
-      # Step to free up disk space
-      #- name: Free disk space
-      #  run: |
-      #    sudo swapoff -a
-      #    sudo rm -f /swapfile
-      #    sudo apt clean
-      #    docker rmi $(docker image ls -aq) || true
-      #    df -h
-
-      # https://github.com/jlumbroso/free-disk-space
-      - name: Free disk space
-        uses: jlumbroso/free-disk-space@main
-        with:
-          # this might remove tools that are actually needed,
-          # if set to "true" but frees about 6 GB
-          tool-cache: false
-          # all of these default to true, but feel free to set to
-          # "false" if necessary for workflow
-          android: true
-          dotnet: true
-          haskell: true
-          large-packages: true
-          docker-images: false
-          swap-storage: true      
-
-      # debug: Step to monitor disk space before build
-      - name: Check disk space before build
-        run: df -h
 
       - name: Cache Docker layers
         uses: actions/cache@v4
